### PR TITLE
mcobbett dependencies via maven repo

### PR DESCRIPTION
**Pull request by techcobweb**
- set-version doesnt add newlines
- correct bug in script which corrupted release.yaml
- managers component supplies release.yaml information via maven repository
- downloads the release.yaml files for manager and framework via maven dependency
- resolve merge conflict
- gradle renames the dependency files to not have versions in.

### CODE REVIEW

**Comment by galasa-team** [comment]
Build failed, see http://localhost:8001/api/v1/namespaces/tekton-pipelines/services/tekton-dashboard:http/proxy/#/namespaces/galasa-build/pipelineruns/repo-obr-pr-130-76qfd for details. If you are unable to do so, please contact a member of the Galasa team.

**Comment by galasa-team** [comment]
Build failed, see http://localhost:8001/api/v1/namespaces/tekton-pipelines/services/tekton-dashboard:http/proxy/#/namespaces/galasa-build/pipelineruns/repo-obr-pr-130-dndmx for details. If you are unable to do so, please contact a member of the Galasa team.

**Comment by galasa-team** [comment]
Build successful

**Comment by galasa-team** [comment]
Build successful

**Comment by galasa-team** [comment]
Build successful

**Review by jadecarino — APPROVED** [review]

**Pull request merged**
