### PR TITLE
Update OBR location in build locally script

### PR DESCRIPTION
**Pull request by jadecarino**
Signed-off-by: Jade Carino <jade.carino@ibm.com>

### CODE REVIEW

**Review by AaronJhaj — APPROVED** [review]

**Comment by galasa-team** [comment]
Build failed, see https://tekton.galasa.dev/#/namespaces/galasa-pipelines/pipelineruns/repo-obr-pr-114-fvskk for details

**Comment by galasa-team** [comment]
Build failed, see https://tekton.galasa.dev/#/namespaces/galasa-pipelines/pipelineruns/repo-obr-pr-114-2t9vh for details

**Comment by galasa-team** [comment]
Build failed, see https://tekton.galasa.dev/#/namespaces/galasa-pipelines/pipelineruns/repo-obr-pr-114-74cpk for details

**Comment by galasa-team** [comment]
Build successful

**Pull request merged**
