### PR TITLE
Iss1942 - Update workflows for OBR, Javadoc and OBR embedded artefacts

### PR DESCRIPTION
**Pull request by jadecarino**
## Why?

- Fixed indentation
- Updated some parts for readability
- Some corrections

### CODE REVIEW

**Comment by galasa-team** [comment]
Build successful

**Comment by galasa-team** [comment]
Build successful

**Comment by galasa-team** [comment]
Build successful

**Review by eamansour — APPROVED** [review]

**Comment by galasa-team** [comment]
Build successful

**Pull request merged**
